CREATE TABLE "tb_patient" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_auth" INTEGER UNIQUE,
  "email" VARCHAR(100),
  "is_active" BOOLEAN,
  "cpf" VARCHAR(11),
  "password" varchar(100),
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP,
  "deleted_at" TIMESTAMP
);

CREATE TABLE "tb_doctor" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_auth" INTEGER UNIQUE,
  "email" VARCHAR(100),
  "is_active" BOOLEAN,
  "is_reviewer" BOOLEAN,
  "crm" VARCHAR(6) UNIQUE,
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP,
  "deleted_at" TIMESTAMP
);

CREATE TABLE "tb_available" (
  "id" INTEGER PRIMARY KEY,
  "id_doctor" INTEGER NOT NULL,
  "month" INTEGER,
  "datetime_available" TIMESTAMP,
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP,
  "deleted_at" TIMESTAMP
);

CREATE TABLE "tb_consults" (
  "id_patient" INTEGER,
  "id_doctor" INTEGER,
  "month" INTEGER,
  "description" VARCHAR(255),
  "datetime_available" TIMESTAMP,
  "hour" TIME,
  "created_at" TIMESTAMP,
  PRIMARY KEY ("id_patient", "id_doctor")
);

CREATE TABLE "tb_auth" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auth_name" VARCHAR(15)
);

CREATE TABLE "tb_questions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_text" TEXT,
  "question_type" VARCHAR(20),
  "is_active" BOOLEAN
);

CREATE TABLE "tb_question_options" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_question" INTEGER NOT NULL,
  "option_text" VARCHAR(100),
  "option_value" numeric UNIQUE
);

CREATE TABLE "tb_user_answers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_patient" INTEGER,
  "id_doctor" INTEGER,
  "id_question_option" INTEGER,
  "id_question" INTEGER NOT NULL,
  "awnser_value" TEXT
);

CREATE TABLE "tb_documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_patient" INTEGER,
  "id_doctor" INTEGER,
  "path" VARCHAR(100),
  "name" VARCHAR(100),
  "status" VARCHAR(20) -- 'approved', 'reviewing', 'denied'
);

ALTER TABLE "tb_patient" ADD FOREIGN KEY ("id_auth") REFERENCES "tb_auth" ("id");

ALTER TABLE "tb_user_answers" ADD FOREIGN KEY ("id_patient") REFERENCES "tb_patient" ("id");

ALTER TABLE "tb_user_answers" ADD FOREIGN KEY ("id_question") REFERENCES "tb_questions" ("id");

ALTER TABLE "tb_question_options" ADD FOREIGN KEY ("id_question") REFERENCES "tb_questions" ("id");

ALTER TABLE "tb_user_answers" ADD FOREIGN KEY ("id_question_option") REFERENCES "tb_question_options" ("id");

ALTER TABLE "tb_doctor" ADD FOREIGN KEY ("id_auth") REFERENCES "tb_auth" ("id");

ALTER TABLE "tb_available" ADD FOREIGN KEY ("id_doctor") REFERENCES "tb_doctor" ("id");

ALTER TABLE "tb_documents" ADD FOREIGN KEY ("id_doctor") REFERENCES "tb_doctor" ("id");

ALTER TABLE "tb_consults" ADD FOREIGN KEY ("id_patient") REFERENCES "tb_patient" ("id");

ALTER TABLE "tb_consults" ADD FOREIGN KEY ("id_doctor") REFERENCES "tb_doctor" ("id");

ALTER TABLE "tb_user_answers" ADD FOREIGN KEY ("id_doctor") REFERENCES "tb_doctor" ("id");


ALTER TABLE tb_available
ADD time time;

alter table tb_doctor
add passowrd VARCHAR(100);

ALTER TABLE tb_doctor
RENAME COLUMN passowrd TO password;

CREATE TABLE "tb_blacklisted_documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" NUMERIC,
  "process" VARCHAR(300)
);